repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.38.0
    hooks:
      - id: eslint
        types_or: [javascript, jsx, ts, tsx]
        args: [--max-warnings=0]

  - repo: local
    hooks:
      - id: prettier-check
        name: prettier
        entry: npx prettier --check
        language: node
        types_or: [javascript, jsx, ts, tsx, css, scss, markdown, json, yaml]
        require_serial: true
